#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run formatting commands
npm run format:php
npm run format:blade

# Check if there are any staged changes
if git diff --cached --quiet; then
    echo "No changes detected. Skipping commit."
    exit 0
fi

echo "Changes detected. Proceeding with commit."